#使用IP
eureka:
  instance:
    prefer-ip-address: true
        #注册ID用默认就好，默认为 ip:hostname:port
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#时区
spring:
  jackson:
    time-zone: GMT+8

#JMX
endpoints:
  jmx:
    unique-names: true

management:
  security:
    enabled: false
  health:
    db:
      enabled: false

security:
  basic:
    enabled: false
    
#JettyPort
server:
  port: 9003