server:
  port: 9002

#使用IP
eureka:
  instance:
    perferIpAddress: true

#时区
spring:
  jackson:
    time-zone: GMT+8
  cloud:
    gateway:
      discovery:
        locator:
          #启用eureka自动查找服务
          enabled: true
          #服务名不区分大小写
          lowerCaseServiceId: true
#eureka客户端ribbon刷新时间,默认30s
ribbon:
  ServerListRefreshInterval: 10000

#admin 允许监控所有接口
management:
  endpoints:
    web:
      exposure:
        include: "*"