#使用IP
eureka:
  instance:
    perferIpAddress: true
    #注册ID用默认就好，默认为 ip:hostname:port
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    
#时区
spring:
  jackson:
    time-zone: GMT+8
    
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: 123456

#JMX

#重定向保证host内容相同
zuul:
  add-host-header: true

#SpringPort
server:
  port: 9002
