#时区
spring:
  jackson:
    time-zone: GMT+8

#SpringPort
server:
  port: 9000

management:
  security:
    enabled: false
  health:
    db:
      enabled: false

security:
  basic:
    enabled: false

#eurekaService
#注释此行，自动去检测主机名
#eureka.instance.hostname=one

#健康检查
eureka:
  client:
    healthcheck:
      enabled: true
