#时区
spring:
  jackson:
    time-zone: GMT+8
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: 123456

management:
  security:
    enabled: false
  health:
    db:
      enabled: false

security:
  basic:
    enabled: false

#健康检查
eureka:
  client:
    healthcheck:
      enabled: true
