#时区
spring:
  jackson:
    time-zone: GMT+8

management:
  security:
    enabled: false
  health:
    db:
      enabled: false

security:
  basic:
    enabled: false

#健康检查
eureka:
  client:
    healthcheck:
      enabled: true
