#使用IP
eureka:
  instance:
    prefer-ip-address: true
        #注册ID用默认就好，默认为 ip:hostname:port
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#时区
spring:
  jackson:
    time-zone: GMT+8
    
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: 123456
    
  redis:
    database: 0
    host: redis
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

#JMX
endpoints:
  jmx:
    unique-names: true

management:
  security:
    enabled: false
  health:
    db:
      enabled: false

security:
  basic:
    enabled: false
    
#JettyPort
server:
  port: 9004